apiVersion: v1
data:
  AWS_PASSWORD: VFJJJGNIWXskVm9sYjUy
  AWS_USERNAME: cHVncmVlbkB5YWhvby5jb20=
kind: Secret
metadata:
  creationTimestamp: "2020-03-22T20:30:18Z"
  name: aws-secret
  namespace: default
  resourceVersion: "6170"
  selfLink: /api/v1/namespaces/default/secrets/aws-secret
  uid: 3c0a6193-b26f-4387-9903-c2327124fc4b
type: Opaque
